name: time_of_war
description: "Time_of_waR application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  workmanager: ^0.6.0
  image_cropper: ^8.0.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5
  home_widget: ^0.9.3
  image_picker: ^1.1.1
  android_alarm_manager_plus: ^5.1.0

dev_dependencies:
  image_cropper: ^8.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
